import 'package:flutter/material.dart';

const Color secondaryColor = Color(0xffF37021);
const Color firstColor = Color(0xffFCAF17);
const Color whiteColor = Color(0xffFFFFFF);
const Color titleColor = Color(0xff58574B);
const Color blackColor = Color(0xff000000);
const Color yellowColor = Color(0xffFFD611);
const Color greyColor = Colors.grey;
const Color lightFontColor = Color(0xFF818386);
const Color textBgColor = Color(0xFFE6E7EE);
const Color fontColor = Color(0xff2A354F);
const Color bgColor = Color(0xffF4F6F9);
const Color bgDarkColor = Color(0xff323B4C);
const Color darkFontColor = Color(0xff1C1B1B);
const Color subFontColor = Color(0xff5D607F);
const Color dangerColor = Color(0XFFCE1B1B);
const Color textFieldColor = Color(0XFFEEF0F6);
const Color iconColor = Color(0XFFB3B3B3);
const Color greenColor = Color(0XFF5ECB6F);
const Color ourGreenColor = Color(0XFF00BE4C);
const Color ourBlueColor = Color(0xff147AD6);
const Color darkThemePrimaryColor = Color(0xff3A3A3A);